// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skladhnedxttlbgscroi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbGFkaG5lZHh0dGxiZ3Njcm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Mzc2MzYsImV4cCI6MjA2NzQxMzYzNn0.Nc9uN5caRIFe7yZe_S-Sr85LjvZlXQXYv8ahupBeWp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});